# Generated by Django 5.0 on 2023-12-07 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="user_photo",
            field=models.ImageField(blank=True, upload_to="user_photo"),
        ),
    ]
