# Generated by Django 4.2.7 on 2023-12-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_details_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="details",
            name="activity",
            field=models.CharField(
                blank=True,
                choices=[
                    (
                        "Сидячий (мало или отсутствует физическая активность)",
                        "Сидячий (мало или отсутствует физическая активность)",
                    ),
                    (
                        "Легкая активность (1-3 дня в неделю)",
                        "Легкая активность (1-3 дня в неделю)",
                    ),
                    (
                        "Умеренная активность (3-5 дней в неделю)",
                        "Умеренная активность (3-5 дней в неделю)",
                    ),
                    (
                        "Очень активный (6-7 дней в неделю)",
                        "Очень активный (6-7 дней в неделю)",
                    ),
                    (
                        "Супер активный (два раза в день)",
                        "Супер активный (два раза в день)",
                    ),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="details",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="details",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="details",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="details",
            name="weight",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
